name: Destroy terraform

on:
  workflow_dispatch:


jobs:
  plan:
    name: Terraform plan
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Setup terraform
        uses:  hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7


      - name: Terraform init
        run: |
          terraform init          
          

      - name: Terraform destroy
        run: |
          terraform destroy -auto-approve -input=false